spring:
  datasource:
    url: jdbc:mysql://${database.jdbc.url}/${database.name}?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: com.springboot.project.common.database.CustomMySQLDialect
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          "[time_zone]": UTC
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  liquibase:
    enabled: true
    change-log: classpath:liquibase/index.xml
  h2:
    console:
      enabled: false
  mail:
    host: smtp.163.com
    username: zdu_20230408001@163.com
    password: INCFTHKUALEWKKTK
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  task:
    scheduling:
      pool:
        size: 50
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    time-zone: UTC
logging:
  level:
    org:
      hibernate:
        dialect:
          function:
            TemplateRenderer: ERROR
        SQL: OFF
        orm:
          jdbc:
            bind: OFF
server:
  error:
    include-message: always
    include-stacktrace: never
  tomcat:
    max-http-form-post-size: -1
  max-http-header-size: 40KB
properties:
  storage:
    root:
      path: ${storage.root.path}
    cloud:
      aliyun:
        enabled: ${storage.cloud.aliyun.enabled}
        endpoint: ${storage.cloud.aliyun.endpoint}
        bucketName: ${storage.cloud.aliyun.bucketName}
        accessKeyId: ${storage.cloud.aliyun.accessKeyId}
        accessKeySecret: ${storage.cloud.aliyun.accessKeySecret}
  is:
    test:
      or:
        dev:
          mode: ${is.test.or.dev.mode}
